# Generated by Django 5.2.4 on 2025-10-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_certificate_url_alter_certificate_issuer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_translations', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_app.skillcategory'),
        ),
    ]
