# Generated by Django 5.2.4 on 2025-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_alter_experience_start_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='descriptions',
            field=models.JSONField(default=list),
        ),
    ]
