# Generated by Django 5.2.4 on 2025-10-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0006_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='descriptions',
        ),
        migrations.CreateModel(
            name='ExperienceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cv_app.experience')),
            ],
        ),
    ]
