# Generated by Django 5.2.4 on 2025-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0007_remove_experience_descriptions_experiencedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='second_end_month',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='second_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='second_start_month',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='second_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
