# Generated by Django 5.2.4 on 2025-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0008_experience_second_end_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='title_translations',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='title_ar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='title_es',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='title_fr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
