# Generated by Django 5.2.4 on 2025-10-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0009_remove_skillcategory_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_year', '-start_month']},
        ),
    ]
